### ISSUE TITLE
2020.1 release tracking issue

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1029]
[These items](https://github.com/pymor/pymor/issues?q=is%3Aopen+milestone%3A2020.1+NOT+tracking) are still open for the 2020.1 milestone.

Release Checklist
--------------------------
 1. [x] (Create release branch)
 1. [x] With each 20XX.1 release, update Copyright notices accordingly
 1. [x] Fix release date in release notes
 1. [x] Update https://github.com/pymor/docs/index.html to point to new release
 1. [x] Check wheel install on debian stretch produces an OK error message due to too old python
 1. [x] Write Release Notes. All new deprecations need to be mentioned.
 1. [x] Update Readme
 1. [x] Update Homepage
 1. [x] Tag commit
 1. [x] Push tag
 1. [x] bump/create demo docker
 1. [x] Wait for CI build to finish (this will upload sdist+wheels to pypi, conda builds to conda cloud)
 1. [x] Make a github release. Zenodo is hooked into that.
 1. [x] update morwiki https://morwiki.mpi-magdeburg.mpg.de/morwiki/index.php/PyMOR
 1. [x] update researchgate https://www.researchgate.net/project/pyMOR-Model-Order-Reduction-with-Python
 1. [x] Submit release to NA-digest: http://icl.utk.edu/na-digest/websubmit.html
 1. [x] Send release announcement to pymor-dev
 1. [x] add a new section in https://github.com/pymor/docker-all/blob/master/docs/releases/Dockerfile
 1. [x] all developers check if (stale) branches can be pruned
 1. [x] Remove deprecated features in master
 1. [x] close the GH milestone for the release https://github.com/pymor/pymor/milestones

**Comment by renefritze** [comment]
There now no open items for 2020.1 @pymor/pymor-devs 

If there's no objection I'll do the release tomorrow morning.

**Comment by sdrave** [comment]
> If there's no objection I'll do the release tomorrow morning.

No objections. Feel free to also post the release announcements ...

**Comment by renefritze** [comment]
Release branch is now live

**Comment by renefritze** [comment]
And 2020.1.1 is now in the pipeline, yay :roll_eyes:

**Comment by renefritze** [comment]
Discovered a twine bug in the sdist upload, but everything's on pypi now. 

@pmli can you do the morwiki update?

**Comment by pmli** [comment]
> @pmli can you do the morwiki update?

Done. (It would be good to also add https://morwiki.mpi-magdeburg.mpg.de/morwiki/index.php/Comparison_of_Software to the checklist. I'll open a PR eventually.)

**Comment by renefritze** [comment]
Great, thanks!

Feel free to add the item in #1031

**Comment by renefritze** [comment]
Conda packages are delayed a bit: https://github.com/conda-forge/pymor-feedstock/pull/11#pullrequestreview-453980535

**Comment by renefritze** [comment]
Conda packages are now also out. 

Reminder to all us @pymor/pymor-devs to  check if (stale) branches can be pruned

**Comment by sdrave** [comment]
> Reminder to all us @pymor/pymor-devs to check if (stale) branches can be pruned

Did that for my branches ...

**Comment by pmli** [comment]
Same here.
